== $section$ Group

*Examples* $quad$ 
- Permutation / symmetric group $"S"_x, X:$ non-empty set. $ "S"_X:={"bijections" X attach(->,t:sigma,b:"1:1") X} $ Multiplication = $compose,$ unit = $id_X,$ $sigma^(-1)$ = inverse map of $sigma.$

- Alternating group / 交错群 $"A"_n:={sigma in S_n | "sgn"(sigma)=1} subset S_n:$ subgroup.

- General linear group / 一般线性群

 Let $V:F$-vector space, $"GL"(V):={"isomorphisms" V arrow.tilde V}$

 - Special linear group / 特殊线性群
 
  $dim V<infinity: "SL"(V):={T in "GL"(V) | det T=1} subset "GL"(V):$ subgroup.

- Orthogonal group / 正交群

 Let $V:$ IPS$\/_RR, dim < infinity.$ $"O"(V):={T:V arrow.tilde V "as IPS"\/_RR}.$

 $"SO"(V):="O"(V) inter "SL"(V).$

- Unitary group / 酉群

 The $CC$ version of orthogonal group. Includes $"U"(V),"SU"(V).$

- Variants for matrices: 

 $"GL"(n,F):={A in M_(n times n)(F) | "invertible"},$

 $"SL"(n,F):={A in "GL"(n,F) | det A=1} subset "GL"(n,F),$

 $"O"(n):={A in "GL"(n,F) | attach(A,tl:t)A=1_(n times n)},$

 $"SO"(n):="SL"(n,RR) inter "O"(n),$

 $"U"(n), "SU"(n)$ are similar.

- $(ZZ,+)$ with unit = 0, $(ZZ\/n ZZ,+)$ with unit  = the class $n ZZ.$

  Note that both groups are abelian.

 In general $(R,+,dot):$ ring $==> (R,+):$ group with unit = $0_R.$

- $R$ ring $==> R^times$ is a group w.r.t. multiplication, unit = $1_R.$

*Notation* $quad G$ group, $S subset G$ as subset, $ angle.l S angle.r :={s_1^(a_1) dots s_n^(a_n) | n in ZZ_(>=0),s_i in S, a_i in ZZ} subset G $ as subgroup, and is the smallest subgroup of $G$ containing $S.$

We say $S$ is a family of generators of $G,$ iff $angle.l S angle.r=G.$

*Examples* $quad$ $"S"(n)$ is generated by $s_i=(i quad i+1),$ $ZZ\/n ZZ$ is generated by $1+n ZZ.$ 

If $n>1,$ then $k+n ZZ$ generates $ZZ\/n ZZ<==>gcd(k,n)=1.$

#pagebreak()

*Definition* $quad$ Let $(G_i)_(i in I)$ be a family of groups. Endow $display(product_(i in I) G_i)$ with the binary operation $ (g_i)_(i in I) (g'_i)_(i in I):=(g_i g'_i)_(i in I) $ then $display(product_(i in I)G_i)$ is a group with unit $= (1_(G_i))_(i in I), (g_i)_(i in I)^(-1)=(g_i^(-1))_(i in I).$

We call $display(product_(i in I)G_i)$ the direct product of $(G_i)_(i in I).$ \ If $forall i, G_i=G,$ then we write $G^I.$ If $I={1,dots,n}$ is finite, write $G_1 times dots times G_n.$

This construction is "associative" (by removing brackets): $ (G_1 times G_2) times G_3 attach(<->,t:"1:1") G_1 times G_2 times G_3 attach(<->,t:"1:1") G_1 times (G_2 times G_3). $

How do we show that they are the "same" groups?

== $section$ Homomorphisms and isomorphisms

General paradigm: homomorphism "are" structure-preserving maps.

*Definition* $quad G,G'$ groups. A map $f:G->G'$ is a homomorphism if $ f(x y)=f(x)f(y),forall x,y in G. $

*Properties* $quad$ If $f$ is a homomorphism, then 

- $f(1_G)=1_G', because f(1_G)=f(1_G 1_G)=f(1_G)f(1_G).$

- $f(x^(-1))=f(x)^(-1), because f(x^(-1))f(x)=f(1_G)=f(x)f(x^(-1)).$

*Remark* $quad$ Homomorphism between semigroups $f(x y)=f(x)f(y),$

between monoid $f(x y)=f(x)f(y), f(1)=1$ (not automatic).

*Examples* $quad id_G:G->G;$ inclusion $H subset G$ ($H$ subgroup); $"sgn":"S"_n->{plus.minus 1};$ \ $det: "GL"(n,F)->F^times$ ($F$ field), $M_(n times n)(F)->F$ (homo. of monoid); 

$(G_i)_(i in I)$ family of groups, $forall j in I, p_j:display(product_(i in I)G_i ->G_j)$ (projection).

$G attach(-->,t:g) G' attach(-->,t:f) G'', f,g$ homomorphism $==>$ so is $f g$ by checking definition.

*Definition* $quad$ Let $f:G->G', g:G'->G$ be homomorphisms. If $g f=id_G$, we say $g$ is a left inverse of $f$. Right inverse is similar. We say they are mutually inverse if $f g=id_G', g f=id_G.$ Note that $g$ is determined by $f:g=f^(-1)$ as maps. In this case, we say $f$ is an isomorphism, $g=$ its inverse which is also an isomorphism.

*Examples* $quad G attach(arrow.tilde, b:id_G) G,$ composition of $arrow.tilde$ is still $arrow.tilde.$ 

Given $G,G',$ if $exists f:G->G'$ isomorphism, we say $G$ and $G'$ are isomorphic, write $G tilde.eq G'$.

*Proposition* $quad$ Let $f:G->G'$ be a bijective homomorphism, then $f$ is $tilde.eq$ of groups.

*Proof* $quad$ To check: the inverse map $f^(-1):G'->G$ (between sets) is a homomorphism. #h(1fr) $square.stroked$

Ditto for semigroups / monoids.

*Examples*

- $G_1 times (G_2 times G_3) tilde.eq G_1 times G_2 times G_3 tilde.eq (G_1 times G_2) times G_3.$

- $F$ field, $V:F$-vs., $dim V=:n<infinity.$ $ "GL"(V) tilde.eq "GL"(n,F),quad T|-> "the matrix of" T, $ after choosing some ordered basis (not unique).

- $V$ IPS$\/_RR, dim V=n. "O"(V) tilde.eq "O"(n).$
 
 $W$ IPS$\/_CC, dim W=n. "U"(W) tilde.eq "U"(n).$

- $V:={id,sigma,tau,sigma tau} subset "S"_4$ subgroup: \ $sigma=(2 thick 1 thick 3 thick 4), tau=(3 thick 4 thick 1 thick 2).$ Then $sigma tau=(4 thick 3 thick 2 thick 1)=tau sigma.$

- $V':={display(mat(1,;,1)),display(mat(1,;,-1)),display(mat(-1,;,1)),display(mat(-1,;,-1))} subset "GL"(2,QQ)$ subgroup.

- $G$ group, $g in G.$ $"Ad"_g: G->G, x |->g x g^(-1)==>$ isomorphism. \ $"Ad"_g "Ad"_h="Ad"_(g h), "Ad"_1=id.$ Hence $"Ad"_g^(-1)="Ad"_(g^(-1)).$

- $"Aut"(G):={"automorphisms of" G}$ is a group w.r.t. composition, $1_G=id.$ \ $==> g|->"Ad"_g$ is a homomorphism of groups.