Structure Theorem for finitely generated $R$-modules, $R$ PID

*Uniqueness* $quad$ To show: if $ M tilde.eq R\/I_1 plus.circle dots plus.circle R\/I_k plus.circle E \ M tilde.eq R\/I'_1 plus.circle dots plus.circle R\/I'_k plus.circle E' $ then $k=k',forall i, I_i tilde.eq I'_i, E tilde.eq E'.$

*Proof* $quad M_"tors" subset M, M_"tf"=M\/M_"tors".$ Their formation is canonical: If $M tilde.eq M'$ then $M_"tors" tilde.eq M'_"tors"$ ($plus.circle.big_i R\/I_i tilde.eq plus.circle.big_j R\/I'_j$) and $M_"tf" tilde.eq M'_"tf"$ ($E tilde.eq E'$).

Reduce to the case $E={0}=E'.$ $M arrow.tilde M' ==> M[p^oo] tilde.eq M'[p^oo]$ for $forall p$. Pass from invariant factors to elementary factors $==>$ it suffices to show: given a prime $p$ in $R,$ if $ M:=plus.big_(i=1)^k  R\/(p^(b_1)) tilde.eq plus.big_(i=1)^k' R\/(p^(b'_i))=:M'  $ then $k=k',$ and $forall i, b_i=b'_i.$

Note that $ M[p]=plus.big_i (R\/(p^(b_i)))[p]=plus.big_i p^(b_i-1)R\/p^(b_i)R tilde.eq plus.big_i R\/(p) $ is naturally $R\/(p)$-vector space (Recall: $R\/(p)$ is  a field), $dim_(R\/(p))M[p]=k.$

More generally: $forall j>=0,$ $ p^j M tilde.eq plus.big_i ("image of" p^j R "in" R\/p^(b_i)R)=plus.big_(i:j<b_i)p^j R\/p^(b_i)R tilde.eq plus.big_(i:j<b_i) R\/p^(b_i-j)R $ $==> (p^j M)[p]$ has $dim_(R\/(p))=$ the number of $i$ s.t. $j<b_i=:nu_j.$ Likewise get $nu'_j$ for $M'.$

$M tilde.eq M' ==> forall j, (p^j M)[p] tilde.eq (p^j M')[p],$ i.e. $nu_j=nu'_j.$ Magic gives $forall i, b_i=b'_i.$ #h(1fr) $square.stroked$

Remains to prove the Lemma: $R$ PID, $E$ free module with rank $=n in ZZ_(>=0), N subset E$ submodule \ $==> exists$ basis $f_1,dots,f_n$ of $E,$ $d_1 bar dots bar d_n$ in $R$ s.t. ${d_i f_i bar d_i!=0}$ is a basis of $N.$

== $section$ Smith normal form of matrices 

$R$ commutative ring, $n,m in ZZ_(>=1), M thick R$-module.

For $e_1,dots,e_n in M, x_1, dots,x_m in M,A=(a_(i j))_(i,j) in M_(n times m) (R), (x_1 dots x_m)=(e_1 dots e_n)A$ means: $ x_j = sum_(i=1)^n e_i a_(i j), quad quad forall j=1,2,dots,m. $

*Facts*

- $(e_1 dots e_n)(A B)=((e_1 dots e_n)A)B,$

- $(e_1 dots e_n) 1_(n times n)=(e_1 dots e_n),$

- If $e_1, dots,e_n in M $ are linearly independent, then the $A$ s.t. $(x_1 dots x_n)=(e_1 dots e_n)A$ is uniquely determined by $x_i$ and $e_j.$

$"GL"(n,R):={A in M_(n times n) (R)|exists B in M_(n times n) (R),A B=1_(n times n)=B A}={A in M_(n times n):det A in R^times}.$

*Facts*

- If $(y'_1 dots y'_n)=(y_1 dots y_n)P, P in "GL"(n,R),$ then $sum R y_i=sum R y'_i.$

  - $supset$ is clear. Multiply $P^(-1)$ on both sides to get $subset.$

- Assume $M$ free, $e_1,dots,e_n$ basis of $M.$ $(e'_1 dots e'_n)=(e_1 dots e_n)A, A$ unqiue. Then $e'_1,dots,e'_n$ form a basis of $M <==> A in "GL"(n,R).$

  - $==>: quad exists! B$ s.t. $(e_1,dots,e_n)=(e'_1,dots,e'_n)B==>A B=1.$ Similarly $B A=1.$

  - $<==: quad sum R e'_i=sum R e_i=M.$ Linear independence: if $sum e'_i b_i=0$ i.e. $ (e'_1 bar dots bar e'_n) mat(b_1;dots.v;b_n)=(e_1 bar dots bar e_n) A mat(b_1;dots.v;b_n)=0, $ hence $A attach((b_1 bar dots bar b_n),tl:t)==>forall i, b_i=0.$ #h(1fr) $square.stroked$

Let $E$ free with basis $e_1,dots,e_n, N subset E$ submodule generated by $x_1,dots,x_m.$ Take the unique $A in M_(n times m) (R)$ s.t. $ (x_1 bar dots bar x_m)=(e_1 bar dots bar e_n) A $

*Observe*: $A ->A P, P in "GL"(n,R) <==>$ replace $(x_1 bar dots bar x_m)$ by $(x'_1 bar dots bar x'_m)=(x_1 bar dots bar x_m) P$  \ $<==>$ change of generators of $N.$ Similarly $A->Q A$ represents a change of basis of $E.$

*Theorem (H. J. S. Smith)* $quad$ Let $R$ PID, $A in M_(n times m) (R),$ then $exists P in "GL"(m,R), Q in "GL"(n,R)$ s.t. $ A=Q "diag"(d_1,d_2,dots) P $ where $d_1 bar d_2 bar dots$ in $R.$

*Proof of Lemma* $quad$ Given $E$ free, say with a basis $e_1,dots,e_n, N subset E$ submodule.

- $N$ is finitely generated (omitted).

- Take generators $x_1,dots,x_m$ of $N.$ Take $A$ s.t. $(x_1 bar dots bar x_m)=(e_1 bar dots bar e_n) A, A=Q "diag"(d_i)P.$ \ Hence $underbracket((x_1 bar dots bar x_m)P^(-1), "generators of" N)=underbracket((e_1 bar dots bar e_n) Q, "basis of" E) "diag"(d_i)$ \ $==> N$ is generated by $x'_i=d_i f_i, d_1 bar d_2 bar dots .$ #h(1fr) $square.stroked$

*Proof of Smith's Theorem* $quad$ Assume $R=ZZ$ or $F[X], F$ field. Start with the case of $ZZ.$

Among all matrix entries of all $Q A P (Q in M_(n times n) (R), P in M_(m times m) (R)),$ take the one with the minimal $abs(dot)!=0.$ Can move it to $(1,1)$ by multiplying permutation matrices, so may assume it is $a_(11).$

Claim: $a_11 bar a_(1j), forall j>1;quad a_11 bar a_(i 1), forall i>1.$

- If not, say $a_(1j)=a_11 d+r, 0<r<abs(a_11),$ can use elementary column operation $a'_(1j)<-a_(1j)-d a_11$ to get $r$ at $(1,j)==>$ contradiction!

$==>$ may assume $a_(1j)=a_(i 1)=0, forall i,j!=0.$ Define $d_1:=a_11.$

Induction: may multiply $A$ by $"diag"(1,A')$ where $A' in M_((n-1) times (n-1)) (R),$ so may assume \ $A="diag"(d_i)$ where $d_2 bar d_3 bar dots.$ Remains to show $d_1 bar d_2.$

- If not, $d_2=d_1 q+r, 0<r<abs(d_1),$ enforce the following:
  - column 2 minus $q$ times of column 1,
  - row 2 adds row 1.
  Now $(2,2)$-entry is $r$, contradicting the choice of $d_1=a_11.$

For $R=F[X]:$ consider the entry with minimal degree. #h(1fr) $square.stroked$

General PID $R:$ See Exercise.

*Definition* $quad R$ commutative ring. We say $R$ is *Noetherian* if $forall$ chain of ideals $I_1 subset I_2 subset dots$ stabilizes, i.e. $exists i_0$ s.t. $i>=i_0 ==>I_i=I_(i_0).$ 

We say an $R$-module $M$ is Noetherian if $forall$ chain of submodules $M_1 subset M_2 subset dots$ stabilizes. 

$R$ is a Noetherian ring $<==> R$ is Noetherian as an $R$-module.
- submodules of $R=$ ideals.  

*Recall* $quad$ PID are Noetherian.

Observe that Noetherian module $M$ are finitely generated,
- otherwise $R x_1 subset.neq R x_1 + R x_2 subset.neq R x_1 + R x_2+r x_3 subset.neq dots$

*Proposition* $quad$ Assume $R$ commutative ring, $M thick R$-module, $M' subset M$ submodule, $M'':=M\/M'.$ Then $M$ is Noetherian $<==> M',M''$ are both Noetherian.

*Corollary* $quad$ If $M_1,M_2$ are Noetherian, then so is $M_1 plus.circle M_2.$

- $display((M_1 plus.circle M_2)/M_1) tilde.eq M_2.$

*Corollary* $quad R$ PID, $E$ free $R$-module, rank $=n in ZZ_(>=0) ==> E$ is Noetherian (so is its submodule, hence all its submodules are finitely generated).

- $E tilde.eq R plus.circle dots plus.circle R, R$ Noetherian.

*Proof of Proposition*

- $==>$ Easy.

- $<==: quad $ Given  $M_1 subset M_2 subset dots$ in $M,$ set $ M'_i:=M_i inter M', M''_i:=("image of" M_i "in" M'')=(M_i+M')\/M' $ $==> exists i_0, forall i>=i_0, M'_i=M'_(i+1),M''_(i)=M''_(i+1).$ To show: $i>=i_0, M_i supset M_(i+1).$

  $forall x in M_(i+1), exists y in M_i$ s.t. $underbracket(x+M',in M''_(i+1))=underbracket(y+M',in M''_i) ==> x-y in M' inter M_(i+1)=M'_(i+1)=M'_i subset M_i,$ \ hence $x in M_i.$ So $M_(i+1) subset M_i.$ #h(1fr) $square.stroked$